[package]
name = "ai-boot"
description = "飞书问题排查机器人"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
ai-boot-agent.workspace = true
ai-boot-feishu.workspace = true
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
calamine.workspace = true
clap.workspace = true
encoding_rs.workspace = true
fast_image_resize.workspace = true
flate2.workspace = true
futures-util.workspace = true
image.workspace = true
pulldown-cmark.workspace = true
quick-xml.workspace = true
rand.workspace = true
regex.workspace = true
rustix.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
tar.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
zip.workspace = true

[dev-dependencies]
reqwest.workspace = true
tempfile.workspace = true
wiremock.workspace = true

[lints]
workspace = true
